#!/bin/bash

mkdir -p po

xgettext --language=Python --keyword=_ --output=po/mythicos-common.pot usr/bin/* usr/lib/python3/dist-packages/mythiccommon/*.py usr/lib/python3/dist-packages/mythiccommon/installer/*.py usr/lib/mythicos/common/*
